import { FilePlus2, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { prefillManualActivity } from "../bookBuilderApi.js";
import { ManualActivityEditor } from "../components/ManualActivityEditor.jsx";
import { Badge, Pagination } from "../components/StudioPrimitives.jsx";
import { StudioEmpty, StudioError, StudioLoading } from "../components/StudioStates.jsx";
import { useStudioResource } from "../hooks/useStudioResource.js";

const TYPES = ["multiple_choice", "true_false", "typed_gap_fill", "open_answer", "media_audio", "media_video", "scrollable_panel", "image_backed"];
const makeId = (prefix) => `${prefix}_${crypto.randomUUID()}`;
function contentFor(type) { if (type === "multiple_choice") return { questions: [{ id: makeId("question"), prompt: "", options: [{ id: makeId("option"), text: "" }, { id: makeId("option"), text: "" }] }] }; if (type === "true_false") return { statements: [{ id: makeId("statement"), prompt: "" }] }; if (type === "typed_gap_fill") return { items: [{ id: makeId("item"), responseFieldId: makeId("field"), prompt: "", displayGuidance: { case: "", punctuation: "" } }] }; if (type === "open_answer") return { prompt: "", responseGuidance: "" }; if (type === "scrollable_panel") return { blocks: [{ id: makeId("block"), kind: "text", text: "" }] }; if (type === "image_backed") return { backgroundAssetId: "", fields: [] }; return { assetId: "", transcript: "" }; }
function newDraft(type, hierarchyOptions) { const component = hierarchyOptions[0]; const group = component?.groups[0]; const now = new Date().toISOString(); return { schemaVersion: "1.0", activityId: makeId("manual_activity"), status: "draft", sourceMode: "manual", hierarchy: { sourceBookRootKey: component.sourceBookRootKey, componentKey: component.componentKey, effectiveComponentRole: component.effectiveComponentRole, unitGroupKey: group?.unitGroupKey || null, unitGroupNumber: group?.unitGroupNumber ?? null, part: null, hotspotCandidateIds: [] }, type, title: "", instructions: "", content: contentFor(type), presentation: { viewportMode: "fit", viewportSizeMode: "responsive", backgroundReviewRequired: false }, assetReferences: [], dependencyFactIds: [], dependencyEvidenceHashes: {}, stale: false, staleReasons: [], createdAt: now, updatedAt: now }; }

export function ManualActivitiesView({ projectId, routeQuery, authoring }) {
  const [filters, setFilters] = useState({ search: routeQuery.get("search") || "", type: routeQuery.get("type") || "", status: routeQuery.get("status") || "", sourceMode: routeQuery.get("sourceMode") || "", stale: routeQuery.get("stale") || "", page: Number(routeQuery.get("page")) || 1 }); const query = useMemo(() => ({ ...filters, stale: filters.stale || undefined }), [filters]);
  const resource = useStudioResource(`/projects/${encodeURIComponent(projectId)}/manual-activities`, query, `${authoring.revision}:${JSON.stringify(query)}`); const assets = useStudioResource(`/projects/${encodeURIComponent(projectId)}/manual-assets`, null, authoring.revision); const [editing, setEditing] = useState(null); const [newType, setNewType] = useState("multiple_choice"); const [candidateId, setCandidateId] = useState(""); const [error, setError] = useState(null);
  useEffect(() => { setEditing(null); }, [projectId]);
  if (resource.status === "loading" || assets.status === "loading") return <StudioLoading label="Loading manual activity workspace…" />;
  if (resource.status === "error" || assets.status === "error") return <StudioError error={resource.error || assets.error} onRetry={() => { resource.retry(); assets.retry(); }} />;
  const data = resource.data; const open = (activity) => setEditing({ activity, isNew: false });
  async function prefill() { setError(null); try { const result = await prefillManualActivity(projectId, candidateId); setEditing({ activity: result.activity, isNew: true }); } catch (cause) { setError(cause); } }
  return <div className="studio-view-content"><div className="studio-view-heading"><div><span className="studio-eyebrow">Local Publisher authoring</span><h2>Manual Activities</h2><p>Detected candidates remain immutable. Student content and Teacher-only solutions persist in separate local artifacts.</p></div><Badge tone={authoring.writeEnabled ? "warning" : "positive"}>{authoring.writeEnabled ? "Edit mode" : "Approved Student view"}</Badge></div>
    {authoring.writeEnabled && <section className="studio-manual-create"><div><label>New activity type<select value={newType} onChange={(event) => setNewType(event.target.value)}>{TYPES.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><button type="button" className="studio-button primary" disabled={!data.hierarchyOptions.length} onClick={() => setEditing({ activity: newDraft(newType, data.hierarchyOptions), isNew: true })}><FilePlus2 /> Create from scratch</button></div><div><label>Detected Student-safe candidate<select value={candidateId} onChange={(event) => setCandidateId(event.target.value)}><option value="">Choose candidate</option>{data.detectedCandidates.map((item) => <option key={item.activityCandidateId} value={item.activityCandidateId}>{item.title} · {item.type}</option>)}</select></label><button type="button" className="studio-button secondary" disabled={!candidateId} onClick={prefill}>Create manual draft from detected candidate</button></div></section>}
    {error && <div role="alert" className="studio-decision-alert danger">{error.message}</div>}
    <div className="studio-filter-bar"><label><Search aria-hidden="true" /> Search<input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, page: 1 })} /></label><label>Type<select value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value, page: 1 })}><option value="">All</option>{TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><label>Status<select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value, page: 1 })}><option value="">All</option>{["draft", "approved", "archived"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Source<select value={filters.sourceMode} onChange={(event) => setFilters({ ...filters, sourceMode: event.target.value, page: 1 })}><option value="">All</option><option value="manual">Manual</option><option value="detected_candidate_prefill">Detected prefill</option></select></label></div>
    {!data.items.length ? <StudioEmpty title="No manual activities">Create a local draft in edit mode, or adjust the filters.</StudioEmpty> : <><div className="studio-manual-card-grid">{data.items.map((item) => <button type="button" key={item.activityId} onClick={() => open(item)}><span><Badge tone={item.status === "approved" ? "positive" : item.stale ? "danger" : "warning"}>{item.status}</Badge><Badge>{item.type.replaceAll("_", " ")}</Badge></span><strong>{item.title || "Untitled draft"}</strong><small>{item.hierarchy.effectiveComponentRole.replaceAll("_", " ")} · {item.hierarchy.unitGroupNumber ?? "global"}</small><small>{item.sourceMode.replaceAll("_", " ")}{item.stale ? " · stale" : ""}</small></button>)}</div><Pagination pagination={data.pagination} onPage={(page) => setFilters({ ...filters, page })} /></>}
    {editing && <ManualActivityEditor projectId={projectId} initialActivity={editing.activity} expectedRevision={authoring.revision} hierarchyOptions={data.hierarchyOptions} assets={assets.data.items} writeEnabled={authoring.writeEnabled} isNew={editing.isNew} onCommitted={authoring.onCommitted} onClose={() => setEditing(null)} />}
  </div>;
}
