import { Clapperboard, Copy, Image, LayoutGrid, Sparkles } from "lucide-react";
import { useState } from "react";

import { Badge, DefinitionList, Metric } from "../components/StudioPrimitives.jsx";
import { SecurePreview } from "../components/SecurePreview.jsx";
import { AvailabilityNotice, StudioEmpty, StudioError, StudioLoading } from "../components/StudioStates.jsx";
import { useStudioResource } from "../hooks/useStudioResource.js";

export function MenuView({ projectId }) {
  const resource = useStudioResource(`/projects/${encodeURIComponent(projectId)}/menu`, null, projectId);
  const [copied, setCopied] = useState(false);
  if (resource.status === "loading") return <StudioLoading label="Loading menu and branding evidence…" />;
  if (resource.status === "error") return <StudioError error={resource.error} onRetry={resource.retry} />;
  const data = resource.data;
  if (!data.available) return <StudioEmpty title="Menu evidence unavailable">This project profile has not produced menu, branding or GAF artifacts.</StudioEmpty>;
  const copyInstruction = async () => { await navigator.clipboard?.writeText(data.materializeInstruction); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return (
    <div className="studio-view-content">
      <div className="studio-view-heading"><div><span className="studio-eyebrow">Authored home screen evidence</span><h2>Menu &amp; Branding</h2><p>Menu buttons, exact authored bounds, atlas summaries and static GAF metadata.</p></div><Badge tone="warning">GAF not executed</Badge></div>
      <div className="studio-metric-grid four"><Metric label="Menu buttons" value={data.buttons.length} /><Metric label="Atlas families" value={data.atlas?.familyCount ?? "—"} /><Metric label="Atlas regions" value={data.atlas?.regionCount ?? "—"} /><Metric label="Materialized previews" value={data.previews.length} /></div>
      <section className="studio-card" aria-labelledby="menu-buttons-title"><div className="studio-card-title"><LayoutGrid aria-hidden="true" /><div><span className="studio-eyebrow">Destinations and textures</span><h3 id="menu-buttons-title">Menu buttons</h3></div></div><div className="studio-table-scroll"><table className="studio-table"><thead><tr><th>Button</th><th>Destination</th><th>Authored bounds</th><th>Normal</th><th>Hover</th><th>Pressed</th><th>Confidence</th></tr></thead><tbody>{data.buttons.map((button) => <tr key={button.id}><td><strong>{button.name}</strong><small>{button.sourceRelativeLocator}</small></td><td>{button.destination.component}{button.destination.unit !== null ? ` · Unit ${button.destination.unit}` : ""}</td><td>{button.bounds.x ?? "—"}, {button.bounds.y ?? "—"} · {button.bounds.width ?? "—"} × {button.bounds.height ?? "—"}</td><td>{button.states.normal ? "Available" : "Missing"}</td><td>{button.states.hover ? "Available" : "Missing"}</td><td>{button.states.pressed ? "Available" : "Missing"}</td><td>{button.confidence === null ? "—" : `${Math.round(button.confidence * 100)}%`}</td></tr>)}</tbody></table></div></section>
      <div className="studio-two-column">
        <section className="studio-card" aria-labelledby="branding-title"><div className="studio-card-title"><Image aria-hidden="true" /><div><span className="studio-eyebrow">Publisher visual evidence</span><h3 id="branding-title">Branding assets</h3></div></div><DefinitionList items={[["Menu title kind", data.branding?.menuTitleKind], ["Startup intro separate", data.branding?.startupIntroIsSeparate ? "Yes" : "Not confirmed"], ["Branding assets", data.branding?.assets.length ?? 0], ["Declared movie clips", data.branding?.movieClips.length ?? 0]]} />{data.branding?.assets.map((asset, index) => <div className="studio-asset-row" key={`${asset.role}-${index}`}><strong>{asset.role.replaceAll("_", " ")}</strong><span>{asset.width || "—"} × {asset.height || "—"} · {asset.byteSize.toLocaleString()} bytes</span><small>{asset.sourceRelativeLocator}</small></div>)}</section>
        <section className="studio-card" aria-labelledby="gaf-title"><div className="studio-card-title"><Sparkles aria-hidden="true" /><div><span className="studio-eyebrow">Central on-menu title</span><h3 id="gaf-title">GAF timeline summary</h3></div></div>{data.gaf ? <DefinitionList items={[["Mode", data.gaf.status], ["Signature / version", `${data.gaf.signature} / ${data.gaf.version}`], ["Stage", `${data.gaf.stage.width} × ${data.gaf.stage.height} · ${data.gaf.stage.fps ?? "—"} fps`], ["Timeline linkage", data.gaf.timeline.linkage], ["Frames", data.gaf.timeline.frames], ["Timeline objects", data.gaf.timeline.objectCount]]} /> : <p className="studio-muted">No safe GAF summary is available.</p>}<AvailabilityNotice>The Studio reports static metadata only. It does not render or execute GAF, SWF or ActionScript.</AvailabilityNotice></section>
      </div>
      <section className="studio-card studio-intro-separation" aria-labelledby="intro-title"><div className="studio-card-title"><Clapperboard aria-hidden="true" /><div><span className="studio-eyebrow">Separate startup media evidence</span><h3 id="intro-title">Startup intro</h3></div></div><p>{data.startupIntro?.distinctFromMenuTitle ? "The startup intro is explicitly distinct from the central on-menu title animation." : "No distinct startup-intro evidence is available."}</p>{data.startupIntro?.descriptor && <span>{data.startupIntro.descriptor.width} × {data.startupIntro.descriptor.height} · autoplay {data.startupIntro.descriptor.autoPlay ? "enabled" : "disabled"}</span>}</section>
      <section aria-labelledby="materialized-title"><div className="studio-section-heading"><div><span className="studio-eyebrow">Existing review assets</span><h3 id="materialized-title">Materialized raster previews</h3></div></div>{data.previews.length ? <div className="studio-preview-gallery">{data.previews.slice(0, 18).map((preview) => <figure key={preview.previewId}><SecurePreview projectId={projectId} previewId={preview.previewId} alt={preview.label} /><figcaption><strong>{preview.label}</strong><span>{preview.role}</span></figcaption></figure>)}</div> : <div className="studio-command-panel"><p>No materialized menu raster previews are available. Generate them separately from the CLI if needed.</p><code>{data.materializeInstruction}</code><button type="button" className="studio-button secondary" onClick={copyInstruction}><Copy aria-hidden="true" />{copied ? "Copied" : "Copy instruction"}</button></div>}</section>
    </div>
  );
}
