import { AlertOctagon, ListTree } from "lucide-react";
import { useMemo, useState } from "react";

import { DecisionDrawer } from "../components/DecisionDrawer.jsx";
import { Badge, Field, Metric, Pagination } from "../components/StudioPrimitives.jsx";
import { StudioEmpty, StudioError, StudioLoading } from "../components/StudioStates.jsx";
import { useStudioResource } from "../hooks/useStudioResource.js";

function ClusterBrowser({ data, onPage }) {
  if (data.clustersAvailable === false) return <StudioEmpty title="Activity clusters unavailable">This project was created before activity structural-cluster artifacts were recorded.</StudioEmpty>;
  return data.items.length ? <><div className="studio-cluster-grid">{data.items.map((cluster) => <article key={cluster.id}><div><span className="studio-eyebrow">Structural cluster</span><h3>{cluster.id.slice(0, 14)}…</h3></div><Badge>{cluster.candidateCount.toLocaleString()} candidates</Badge><dl><div><dt>Common dispositions</dt><dd>{Object.entries(cluster.dispositions).map(([name, count]) => `${name} (${count})`).join(", ")}</dd></div><div><dt>Common review reasons</dt><dd>{cluster.commonReviewReasons.join(", ") || "No sample reason resolved"}</dd></div></dl><details><summary>Safe source samples</summary><ul>{cluster.samples.map((sample) => <li key={sample}>{sample}</li>)}</ul></details></article>)}</div><Pagination pagination={data.pagination} onPage={onPage} /></> : <StudioEmpty title="No structural clusters match">Choose another grouping or filter.</StudioEmpty>;
}

function ReviewItem({ item, writeEnabled, onDecide }) {
  return <article><div className="studio-review-item-heading"><div><strong>{item.reasonCode.replaceAll("_", " ")}</strong><small>{item.category} · {item.severity}</small></div><div className="studio-inline-badges">{item.blocking && <Badge tone="danger">Blocking</Badge>}<Badge tone={item.effectiveStatus === "open" ? "warning" : item.effectiveStatus === "stale_resolution" ? "danger" : "positive"}>{item.effectiveStatus}</Badge>{item.editorLink && <a className="studio-button secondary" href={item.editorLink}>Open exact field</a>}{writeEnabled && <button type="button" className="studio-button secondary" onClick={() => onDecide(item)}>Review disposition</button>}</div></div><p>{item.explanation}</p><dl><div><dt>Source</dt><dd>{item.sourceRelativeLocator}</dd></div><div><dt>Recommended domain decision</dt><dd>{item.suggestedDecisionKind.replaceAll("_", " ")}</dd></div><div><dt>Dependencies</dt><dd>{item.dependencyCount}</dd></div><div><dt>Generated status</dt><dd>{item.generatedStatus}</dd></div>{item.contentOverride && <><div><dt>Detected</dt><dd>{item.contentOverride.detectedValue || "Missing"}</dd></div><div><dt>Manual / effective</dt><dd>{item.contentOverride.manualValue || "No manual value"} / {item.contentOverride.effectiveValue || "Missing"}</dd></div><div><dt>Resolution progress</dt><dd>{item.effectiveStatus === "resolved" ? "Field completed" : item.contentOverride.stale ? "Manual value is stale" : "Field remains open"}</dd></div></>}</dl></article>;
}

function ReviewItems({ selectedGroup, onPage, writeEnabled, onDecide }) {
  if (!selectedGroup) return <StudioEmpty title="Select a review group">Choose a bounded group to inspect its unresolved items.</StudioEmpty>;
  return <section className="studio-review-items" aria-labelledby="review-items-title"><div className="studio-section-heading"><div><span className="studio-eyebrow">Selected group</span><h3 id="review-items-title">{selectedGroup.id.replaceAll("_", " ")}</h3></div><Badge tone="warning">{selectedGroup.pagination.total.toLocaleString()} items</Badge></div>{selectedGroup.items.map((item) => <ReviewItem key={item.id} item={item} writeEnabled={writeEnabled} onDecide={onDecide} />)}<Pagination pagination={selectedGroup.pagination} onPage={onPage} /></section>;
}

export function ReviewQueueView({ projectId, authoring }) {
  const [filters, setFilters] = useState({ groupBy: "reason", reason: "", category: "", severity: "", component: "", unit: "", groupId: "", page: 1, pageSize: 25 });
  const query = useMemo(() => filters, [filters]);
  const resource = useStudioResource(`/projects/${encodeURIComponent(projectId)}/reviews`, query, JSON.stringify(query));
  const update = (key, value) => setFilters((current) => ({ ...current, [key]: value, ...(key === "page" ? {} : { page: 1 }), ...(["groupBy", "reason", "category", "severity", "component", "unit"].includes(key) ? { groupId: "" } : {}) }));
  const [editing, setEditing] = useState(null);
  if (resource.status === "loading" && !resource.data) return <StudioLoading label="Grouping unresolved review items…" />;
  if (resource.status === "error") return <StudioError error={resource.error} onRetry={resource.retry} />;
  const data = resource.data;
  if (!data.available) return <StudioEmpty title="Review queue unavailable">No review-queue artifact has been recorded for this project.</StudioEmpty>;
  return <div className="studio-view-content">
    <div className="studio-view-heading"><div><span className="studio-eyebrow">Generated queue with effective overlay</span><h2>Review Queue</h2><p>Generated items stay immutable; exact approved field decisions compute effective status locally.</p></div><Badge tone={authoring.writeEnabled ? "positive" : "warning"}>{authoring.writeEnabled ? "Single-item decisions" : "Read-only"}</Badge></div>
    <div className="studio-metric-grid four"><Metric label="Generated reviews" value={data.summary.total.toLocaleString()} /><Metric label="Open" value={data.summary.open.toLocaleString()} /><Metric label="Resolved / deferred" value={(data.summary.resolved + data.summary.deferred).toLocaleString()} /><Metric label="Blocking open" value={data.summary.blockingOpen.toLocaleString()} /></div>
    <div className="studio-filter-grid compact" aria-label="Review filters"><Field label="Group by"><select value={filters.groupBy} onChange={(event) => update("groupBy", event.target.value)}><option value="reason">Reason code</option><option value="category">Category</option><option value="component">Component</option><option value="unit">Unit / group</option><option value="cluster">Activity structural cluster</option><option value="severity">Severity</option><option value="decision">Suggested decision kind</option></select></Field><Field label="Reason"><select value={filters.reason} onChange={(event) => update("reason", event.target.value)}><option value="">All reasons</option>{Object.keys(data.summary.byReason).map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Category"><select value={filters.category} onChange={(event) => update("category", event.target.value)}><option value="">All categories</option>{Object.keys(data.summary.byCategory).map((item) => <option key={item}>{item}</option>)}</select></Field></div>
    {resource.status === "loading" && <div className="studio-inline-loading" role="status">Updating review groups…</div>}
    {data.grouping === "cluster" ? <ClusterBrowser data={data} onPage={(page) => update("page", page)} /> : <div className="studio-review-layout"><aside className="studio-review-groups" aria-label="Review groups"><div className="studio-card-title"><ListTree aria-hidden="true" /><div><span className="studio-eyebrow">Grouping</span><h3>{data.grouping.replaceAll("_", " ")}</h3></div></div>{data.groups.map((group) => <button type="button" key={group.id} aria-pressed={data.selectedGroup?.id === group.id} onClick={() => update("groupId", group.id)}><span><strong>{group.label.replaceAll("_", " ")}</strong><small>{group.blocking.toLocaleString()} blocking</small></span><b>{group.count.toLocaleString()}</b></button>)}</aside><ReviewItems selectedGroup={data.selectedGroup} onPage={(page) => update("page", page)} writeEnabled={authoring.writeEnabled} onDecide={setEditing} /></div>}
    <div className="studio-boundary-note"><AlertOctagon aria-hidden="true" /><p>Cluster grouping remains read-only. Milestone 4B2A permits only one exact field or one explicit review item at a time.</p></div>
    {editing && <DecisionDrawer projectId={projectId} expectedRevision={authoring.revision} target={{ targetId: editing.id, label: editing.reasonCode.replaceAll("_", " "), sourceRelativeLocator: editing.sourceRelativeLocator }} kinds={[{ kind: "review_disposition", label: "Review disposition", values: ["deferred", "not_applicable", "accepted_risk"], initialValue: editing.effectiveStatus === "open" || editing.effectiveStatus === "stale_resolution" ? "deferred" : editing.effectiveStatus, detectedValue: editing.generatedStatus, currentDecision: editing.decision }]} onCommitted={authoring.onCommitted} onClose={() => setEditing(null)} />}
  </div>;
}
