import test from "node:test";
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import bcrypt from "bcryptjs";
import pg from "pg";
import { setSqlForTests, hashToken, sessionCookieName } from "../../netlify/functions/_auth-utils.js";
import { clearCapturedEmailsForTests, getCapturedEmailsForTests, setEmailTransportForTests } from "../../netlify/functions/_email-utils.js";
import { handler as invite } from "../../netlify/functions/account-invite.js";
import { handler as tokenCheck } from "../../netlify/functions/account-token-check.js";
import { handler as setPassword } from "../../netlify/functions/account-set-password.js";
import { handler as forgot } from "../../netlify/functions/auth-forgot-password.js";
import { handler as reset } from "../../netlify/functions/auth-reset-password.js";
import { handler as changePassword } from "../../netlify/functions/auth-change-password.js";
import { handler as revokeSessions } from "../../netlify/functions/auth-revoke-sessions.js";
import { handler as authMe } from "../../netlify/functions/auth-me.js";
import { handler as userHandler } from "../../netlify/functions/user.js";
import { handler as emailDispatch } from "../../netlify/functions/account-email-dispatch.js";
import { applyCanonicalProductionMigrations } from "./_migration-test-helpers.mjs";

const { Pool }=pg;
const url=process.env.TEST_DATABASE_URL||"";
const enabled=Boolean(url)&&process.env.TEST_DATABASE_CONFIRMATION==="isolated-test-database";
function tag(pool){return async(strings,...values)=>{let text=strings[0];for(let i=0;i<values.length;i++)text+=`$${i+1}${strings[i+1]}`;return (await pool.query(text,values)).rows;};}
function scoped(base,schema){const u=new URL(base);u.searchParams.set("options",`-c search_path=${schema}`);return u.toString();}
function parse(r){return {status:r.statusCode,body:JSON.parse(r.body||"{}"),headers:r.headers||{}};}
async function call(handler,{method="POST",body={},cookie="",ip="127.0.9.1",query={},headers={}}={}){return parse(await handler({httpMethod:method,headers:{host:"localhost:8888",cookie,"x-nf-client-connection-ip":ip,...headers},body:method==="GET"?"":JSON.stringify(body),queryStringParameters:query,rawQuery:new URLSearchParams(query).toString()}));}
async function session(pool,id){const token=randomBytes(24).toString("hex");await pool.query("insert into auth_sessions(user_id,token_hash,expires_at) values($1,$2,now()+interval '1 day')",[id,hashToken(token)]);return `${sessionCookieName}=${token}`;}

test("account lifecycle handlers use single-use links, tenant admin scope and session rotation",{skip:!enabled,timeout:120000},async(t)=>{
  const schema=`lifecycle_${randomBytes(6).toString("hex")}`;const adminPool=new Pool({connectionString:url});await adminPool.query(`create schema "${schema}"`);const pool=new Pool({connectionString:scoped(url,schema)});
  const previous={DATABASE_URL:process.env.DATABASE_URL,APP_PUBLIC_URL:process.env.APP_PUBLIC_URL,ACCOUNT_EMAIL_MODE:process.env.ACCOUNT_EMAIL_MODE,STAGING_DATABASE_CONFIRMATION:process.env.STAGING_DATABASE_CONFIRMATION,SMTP_HOST:process.env.SMTP_HOST,SMTP_PORT:process.env.SMTP_PORT,SMTP_SECURE:process.env.SMTP_SECURE,SMTP_USER:process.env.SMTP_USER,SMTP_PASS:process.env.SMTP_PASS,SMTP_FROM:process.env.SMTP_FROM,ACCOUNT_EMAIL_DISPATCH_SECRET:process.env.ACCOUNT_EMAIL_DISPATCH_SECRET};
  process.env.DATABASE_URL=scoped(url,schema);process.env.APP_PUBLIC_URL="http://localhost:8888";process.env.ACCOUNT_EMAIL_MODE="capture";setSqlForTests(tag(pool));clearCapturedEmailsForTests();
  t.after(async()=>{setSqlForTests(null);for(const [key,value] of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}await pool.end();await adminPool.query(`drop schema if exists "${schema}" cascade`);await adminPool.end();});
  await applyCanonicalProductionMigrations(pool);
  const schools=(await pool.query("insert into schools(name) values('Lifecycle A'),('Lifecycle B') returning id,name")).rows;const a=schools[0].id,b=schools[1].id;const pass=await bcrypt.hash("Admin-Original-2026",4);
  const admins=(await pool.query("insert into app_users(school_id,full_name,email,role,status,password_hash) values($1,'Admin A','admin-a@life.test','admin','active',$3),($2,'Admin B','admin-b@life.test','admin','active',$3),($1,'Admin A2','admin-a2@life.test','admin','active',$3) returning id,school_id",[a,b,pass])).rows;
  let cookie=await session(pool,admins[0].id);const cookieB=await session(pool,admins[1].id);
  const studentId=(await pool.query("insert into app_users(school_id,full_name,email,role,status,password_hash) values($1,'Student A','student-a@life.test','student','active',$2) returning id",[a,pass])).rows[0].id;const studentCookie=await session(pool,studentId);
  assert.equal((await call(invite,{cookie:studentCookie,body:{full_name:"No",email:"student-cannot@life.test",role:"student"}})).status,403);
  assert.equal((await call(revokeSessions,{cookie,body:{userId:studentId}})).status,200);assert.equal((await call(authMe,{method:"GET",cookie:studentCookie})).status,401);
  const duplicateRace=await Promise.all([call(invite,{cookie,body:{full_name:"Race Student",email:"race-student@life.test",role:"student"},ip:"127.0.9.50"}),call(invite,{cookie,body:{full_name:"Race Student",email:"race-student@life.test",role:"student"},ip:"127.0.9.51"})]);assert.deepEqual(duplicateRace.map((result)=>result.status).sort(),[201,409]);const raceUserId=(await pool.query("select id from app_users where email='race-student@life.test'")).rows[0].id;assert.equal((await pool.query("select count(*)::int count from account_tokens where user_id=$1 and used_at is null and revoked_at is null",[raceUserId])).rows[0].count,1);assert.equal((await pool.query("select count(*)::int count from account_email_outbox where user_id=$1",[raceUserId])).rows[0].count,1);
  const invited=await call(invite,{cookie,body:{full_name:"Teacher New",email:"teacher-new@life.test",role:"teacher",school_id:b}});assert.equal(invited.status,400);
  assert.equal((await call(invite,{cookie,body:{full_name:"Admin Escalation",email:"admin-new@life.test",role:"admin"}})).status,400);
  const created=await call(invite,{cookie,body:{full_name:"Teacher New",email:"teacher-new@life.test",role:"teacher"}});assert.equal(created.status,201);assert.equal(created.body.user.school_id,undefined);
  const captured=getCapturedEmailsForTests();assert.equal(captured.length,2);const token=new URL(captured.at(-1).actionUrl).hash.split("token=")[1];assert.ok(token);
  assert.equal((await call(tokenCheck,{body:{token,purpose:"initial_password"}})).status,200);
  await pool.query("update account_tokens set expires_at=now()-interval '1 minute' where token_hash=$1",[hashToken(token)]);const expiredResponse=await call(tokenCheck,{body:{token,purpose:"initial_password"}});assert.equal(expiredResponse.status,400);await pool.query("update account_tokens set expires_at=now()+interval '1 day' where token_hash=$1",[hashToken(token)]);
  const resent=await call(invite,{cookie,body:{email:"teacher-new@life.test",resend:true},ip:"127.0.9.8"});assert.equal(resent.status,200);
  const replacement=new URL(getCapturedEmailsForTests().at(-1).actionUrl).hash.split("token=")[1];const revokedResponse=await call(tokenCheck,{body:{token,purpose:"initial_password"}});assert.equal(revokedResponse.status,400);assert.equal(revokedResponse.body.error,expiredResponse.body.error);const invalidResponse=await call(tokenCheck,{body:{token:"z".repeat(43),purpose:"initial_password"}});assert.equal(invalidResponse.body.error,revokedResponse.body.error);
  const wrongPurpose=await call(tokenCheck,{body:{token:replacement,purpose:"password_reset"}});assert.equal(wrongPurpose.body.error,revokedResponse.body.error);
  const weak=await call(setPassword,{body:{token:replacement,password:"short"}});assert.equal(weak.status,400);assert.equal((await pool.query("select used_at from account_tokens where token_hash=$1",[hashToken(replacement)])).rows[0].used_at,null);
  const concurrent=await Promise.all([call(setPassword,{body:{token:replacement,password:"Teacher-Strong-2026"},ip:"127.0.9.30"}),call(setPassword,{body:{token:replacement,password:"Teacher-Strong-2026"},ip:"127.0.9.31"})]);assert.deepEqual(concurrent.map((result)=>result.status).sort(),[200,400]);
  const accepted=concurrent.find((result)=>result.status===200);assert.equal(accepted.body.user.status,"active");assert.equal((await call(setPassword,{body:{token:replacement,password:"Another-Strong-2026"}})).status,400);
  const teacherCookie=accepted.headers["Set-Cookie"].split(";")[0];assert.equal((await call(invite,{cookie:teacherCookie,body:{full_name:"No",email:"no@life.test",role:"student"}})).status,403);assert.equal((await call(revokeSessions,{cookie:teacherCookie,body:{userId:studentId}})).status,403);
  assert.equal((await call(invite,{cookie,body:{email:"teacher-new@life.test",resend:true},ip:"127.0.9.9"})).status,404);
  const unknown=await call(forgot,{body:{email:"missing@life.test"},ip:"127.0.9.2"});const known=await call(forgot,{body:{email:"teacher-new@life.test"},ip:"127.0.9.3"});assert.equal(unknown.status,200);assert.equal(known.status,200);assert.equal(unknown.body.message,known.body.message);
  process.env.STAGING_DATABASE_CONFIRMATION="isolated-staging-database";process.env.ACCOUNT_EMAIL_MODE="preview";const previewUnknown=await call(forgot,{body:{email:"missing-preview@life.test"},ip:"127.0.9.52"});const previewKnown=await call(forgot,{body:{email:"teacher-new@life.test"},ip:"127.0.9.53"});assert.deepEqual(previewKnown.body,previewUnknown.body);assert.equal(previewKnown.body.preview_url,undefined);delete process.env.STAGING_DATABASE_CONFIRMATION;process.env.ACCOUNT_EMAIL_MODE="capture";
  const firstResetToken=new URL(getCapturedEmailsForTests().at(-1).actionUrl).hash.split("token=")[1];assert.equal((await call(reset,{body:{token:firstResetToken,password:"Teacher-Strong-2026"},ip:"127.0.9.34"})).status,400);assert.equal((await pool.query("select used_at from account_tokens where token_hash=$1",[hashToken(firstResetToken)])).rows[0].used_at,null);await call(forgot,{body:{email:"teacher-new@life.test"},ip:"127.0.9.32"});assert.equal((await call(reset,{body:{token:firstResetToken,password:"Teacher-Old-Link-2026"},ip:"127.0.9.33"})).status,400);assert.equal((await pool.query("select count(*)::int count from account_tokens where user_id=$1 and purpose='password_reset' and used_at is null and revoked_at is null",[created.body.user.id])).rows[0].count,1);
  const resetMail=getCapturedEmailsForTests().at(-1);const resetToken=new URL(resetMail.actionUrl).hash.split("token=")[1];const resetResult=await call(reset,{body:{token:resetToken,password:"Teacher-Reset-2026"},ip:"127.0.9.4"});assert.equal(resetResult.status,200);assert.equal((await call(reset,{body:{token:resetToken,password:"Teacher-Replay-2026"},ip:"127.0.9.4"})).status,400);
  assert.equal((await pool.query("select count(*)::int count from auth_sessions where user_id=$1",[created.body.user.id])).rows[0].count,1);
  assert.equal((await call(authMe,{method:"GET",cookie:teacherCookie})).status,401);
  const changed=await call(changePassword,{cookie:resetResult.headers["Set-Cookie"].split(";")[0],body:{currentPassword:"Teacher-Reset-2026",newPassword:"Teacher-Changed-2026"}});assert.equal(changed.status,200);
  assert.equal((await call(revokeSessions,{cookie:cookieB,body:{userId:created.body.user.id}})).status,404);
  assert.equal((await call(revokeSessions,{cookie,body:{userId:admins[2].id}})).status,403);
  assert.equal((await call(revokeSessions,{cookie:changed.headers["Set-Cookie"].split(";")[0],body:{userId:admins[0].id}})).status,403);
  await session(pool,created.body.user.id);assert.equal((await call(revokeSessions,{cookie,body:{userId:created.body.user.id}})).status,200);assert.equal((await pool.query("select count(*)::int count from auth_sessions where user_id=$1",[created.body.user.id])).rows[0].count,0);
  const self=await call(revokeSessions,{cookie,body:{}});assert.equal(self.status,200);assert.ok(self.headers["Set-Cookie"]);cookie=self.headers["Set-Cookie"].split(";")[0];
  for(let i=0;i<5;i++)assert.equal((await call(forgot,{body:{email:"rate-limit@life.test"},ip:"127.0.9.20"})).status,200);
  const limited=await call(forgot,{body:{email:"rate-limit@life.test"},ip:"127.0.9.20"});assert.equal(limited.status,429);assert.equal(limited.headers["Retry-After"],"900");
  await pool.query("update account_rate_limit_attempts set attempted_at=now()-interval '16 minutes' where scope='forgot_password'");assert.equal((await call(forgot,{body:{email:"rate-limit@life.test"},ip:"127.0.9.20"})).status,200);
  await pool.query("update account_rate_limit_attempts set attempted_at=now()-interval '8 days'");await pool.query("select * from cleanup_account_lifecycle_history()");assert.equal((await pool.query("select count(*)::int count from account_rate_limit_attempts where attempted_at<now()-interval '7 days'")).rows[0].count,0);
  const activeCookie=await session(pool,created.body.user.id);const paused=await call(userHandler,{method:"PATCH",cookie,query:{id:created.body.user.id},body:{status:"paused"}});assert.equal(paused.status,200);assert.equal((await call(authMe,{method:"GET",cookie:activeCookie})).status,401);assert.equal((await pool.query("select count(*)::int count from account_security_events where user_id=$1 and event_type='account_paused'",[created.body.user.id])).rows[0].count,1);
  const pausedTokenCount=(await pool.query("select count(*)::int count from account_tokens where user_id=$1",[created.body.user.id])).rows[0].count;assert.equal((await call(forgot,{body:{email:"teacher-new@life.test"},ip:"127.0.9.40"})).status,200);assert.equal((await pool.query("select count(*)::int count from account_tokens where user_id=$1",[created.body.user.id])).rows[0].count,pausedTokenCount);
  process.env.ACCOUNT_EMAIL_MODE="smtp";for(const key of ["SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASS","SMTP_FROM"])process.env[key]="";
  const failedKnownReset=await call(forgot,{body:{email:"student-a@life.test"},ip:"127.0.9.43"});const failedUnknownReset=await call(forgot,{body:{email:"unknown-delivery@life.test"},ip:"127.0.9.44"});assert.equal(failedKnownReset.status,200);assert.deepEqual(failedKnownReset.body,failedUnknownReset.body);assert.equal((await pool.query("select delivery_state from account_email_outbox where user_id=$1 and template_type='password_reset' order by created_at desc limit 1",[studentId])).rows[0].delivery_state,"failed");
  const failedEmail="delivery-failure@life.test";const failedInvite=await call(invite,{cookie,body:{full_name:"Delivery Failure",email:failedEmail,role:"student"},ip:"127.0.9.41"});assert.equal(failedInvite.status,201);assert.equal(failedInvite.body.delivery_status,"failed");assert.equal((await call(invite,{cookie,body:{full_name:"Duplicate",email:failedEmail,role:"student"},ip:"127.0.9.42"})).status,409);assert.equal((await pool.query("select count(*)::int count from app_users where email=$1",[failedEmail])).rows[0].count,1);assert.equal((await pool.query("select delivery_state from account_email_outbox where recipient_email=$1",[failedEmail])).rows[0].delivery_state,"failed");process.env.ACCOUNT_EMAIL_MODE="capture";
  const queuedId=(await pool.query("insert into account_email_outbox(user_id,recipient_email,template_type,template_variables) values($1,'student-a@life.test','password_changed','{\"name\":\"Student A\"}') returning id",[studentId])).rows[0].id;Object.assign(process.env,{ACCOUNT_EMAIL_MODE:"smtp",SMTP_HOST:"smtp.test",SMTP_PORT:"587",SMTP_SECURE:"false",SMTP_USER:"user",SMTP_PASS:"secret",SMTP_FROM:"noreply@eduforge.test",ACCOUNT_EMAIL_DISPATCH_SECRET:"dispatch-test"});setEmailTransportForTests({sendMail:async()=>({messageId:"dispatcher-test"})});const dispatchResults=await Promise.all([call(emailDispatch,{headers:{"x-account-dispatch-secret":"dispatch-test"}}),call(emailDispatch,{headers:{"x-account-dispatch-secret":"dispatch-test"}})]);assert.equal(dispatchResults.reduce((sum,result)=>sum+result.body.claimed,0),1);assert.equal((await pool.query("select delivery_state,attempt_count from account_email_outbox where id=$1",[queuedId])).rows[0].delivery_state,"sent");setEmailTransportForTests(null);process.env.ACCOUNT_EMAIL_MODE="capture";
  const rawSearch=await pool.query("select token_hash,metadata from account_tokens");assert.equal(JSON.stringify(rawSearch.rows).includes(token),false);assert.equal((await pool.query("select count(*)::int count from account_email_outbox where template_variables ? 'token'")).rows[0].count,0);
});
