export const listeningGapFillItems = [
  {
    id: "lgf-1",
    prompt: "Alex says that if they want to be warmer, people should go to the ___ part of the boat.",
    before: "Alex says that if they want to be warmer, people should go to the",
    after: "part of the boat.",
    answer: "lower",
    acceptedAnswers: ["lower"],
  },
  {
    id: "lgf-2",
    prompt: "The river cruise will take ___ hours in total.",
    before: "The river cruise will take",
    after: "hours in total.",
    answer: "four",
    acceptedAnswers: ["four", "4"],
  },
  {
    id: "lgf-3",
    prompt: "A River Pass allows tourists to get off the boat in the ___.",
    before: "A River Pass allows tourists to get off the boat in the",
    after: ".",
    answer: "city centre",
    acceptedAnswers: ["city centre", "city center"],
  },
  {
    id: "lgf-4",
    prompt: "Roman invaders built the first bridge across the Thames ___ ago.",
    before: "Roman invaders built the first bridge across the Thames",
    after: "ago.",
    answer: "2000 years",
    acceptedAnswers: ["2000 years", "2,000 years"],
  },
  {
    id: "lgf-5",
    prompt: "Long ago, many sections of the river would ___ over completely in winter.",
    before: "Long ago, many sections of the river would",
    after: "over completely in winter.",
    answer: "freeze",
    acceptedAnswers: ["freeze"],
  },
  {
    id: "lgf-6",
    prompt: "During 'Frost Fairs', dancing and ___ took place on the ice.",
    before: "During 'Frost Fairs', dancing and",
    after: "took place on the ice.",
    answer: "sports",
    acceptedAnswers: ["sports"],
  },
  {
    id: "lgf-7",
    prompt: "In the 1950s, the Thames was said to be a ___ river.",
    before: "In the 1950s, the Thames was said to be a",
    after: "river.",
    answer: "dead",
    acceptedAnswers: ["dead"],
  },
  {
    id: "lgf-8",
    prompt: "Alex explains that now, even ___ occasionally swim up the river.",
    before: "Alex explains that now, even",
    after: "occasionally swim up the river.",
    answer: "sharks",
    acceptedAnswers: ["sharks"],
  },
  {
    id: "lgf-9",
    prompt: "The movement of sea water can sometimes cause ___ in London.",
    before: "The movement of sea water can sometimes cause",
    after: "in London.",
    answer: "floods",
    acceptedAnswers: ["floods"],
  },
  {
    id: "lgf-10",
    prompt: "Annually, ___ million tourists ride on the London Eye.",
    before: "Annually,",
    after: "million tourists ride on the London Eye.",
    answer: "3.5",
    acceptedAnswers: ["3.5", "three point five"],
  },
];
