export const QUIZ_DURATION_SECONDS = 20 * 60;
export const quiz1Questions = [
  {
    id: "quiz1-1",
    question: "She's a very experienced ___. She's made more than twenty films in the last thirty years.",
    options: ["A. cast", "B. crew", "C. producer", "D. cinemagoer"],
    answer: "C. producer",
  },
  {
    id: "quiz1-2",
    question: "The film had a huge ___ and included several famous actors.",
    options: ["A. cast", "B. review", "C. audience", "D. scene"],
    answer: "A. cast",
  },
  {
    id: "quiz1-3",
    question: "We arrived late and missed the opening ___ of the play.",
    options: ["A. plot", "B. scene", "C. subtitle", "D. critic"],
    answer: "B. scene",
  },
  {
    id: "quiz1-4",
    question: "The documentary was so ___ that I kept thinking about it the next day.",
    options: ["A. thought-provoking", "B. predictable", "C. ordinary", "D. private"],
    answer: "A. thought-provoking",
  },
  {
    id: "quiz1-5",
    question: "The story was easy to follow because the ___ was simple and clear.",
    options: ["A. plot", "B. cast", "C. review", "D. venue"],
    answer: "A. plot",
  },
  {
    id: "quiz1-6",
    question: "The special effects looked completely ___.",
    options: ["A. realistic", "B. ordinary", "C. crowded", "D. native"],
    answer: "A. realistic",
  },
  {
    id: "quiz1-7",
    question: "A person who writes opinions about films, plays, or books is a ___.",
    options: ["A. critic", "B. crew", "C. producer", "D. character"],
    answer: "A. critic",
  },
  {
    id: "quiz1-8",
    question: "The audience gave the actors a standing ___ at the end.",
    options: ["A. ovation", "B. location", "C. direction", "D. reservation"],
    answer: "A. ovation",
  },
  {
    id: "quiz1-9",
    question: "The book was ___ into a successful TV series.",
    options: ["A. adapted", "B. located", "C. performed", "D. released"],
    answer: "A. adapted",
  },
  {
    id: "quiz1-10",
    question: "I usually read a ___ before deciding whether to watch a new film.",
    options: ["A. review", "B. crew", "C. scene", "D. stage"],
    answer: "A. review",
  },
  {
    id: "quiz1-11",
    question: "The lead ___ was excellent and made the character feel real.",
    options: ["A. actor", "B. audience", "C. subtitle", "D. plot"],
    answer: "A. actor",
  },
  {
    id: "quiz1-12",
    question: "This cinema shows foreign films with English ___.",
    options: ["A. subtitles", "B. scenes", "C. reviews", "D. venues"],
    answer: "A. subtitles",
  },
  {
    id: "quiz1-13",
    question: "The concert ___ was full, so we had to stand at the back.",
    options: ["A. venue", "B. plot", "C. critic", "D. cast"],
    answer: "A. venue",
  },
  {
    id: "quiz1-14",
    question: "The main character has to ___ a difficult choice at the end.",
    options: ["A. make", "B. do", "C. have", "D. take"],
    answer: "A. make",
  },
  {
    id: "quiz1-15",
    question: "The ending was very ___; everyone guessed it halfway through.",
    options: ["A. predictable", "B. realistic", "C. moving", "D. powerful"],
    answer: "A. predictable",
  },
  {
    id: "quiz1-16",
    question: "I found the final scene very ___ and almost cried.",
    options: ["A. moving", "B. crowded", "C. ordinary", "D. private"],
    answer: "A. moving",
  },
  {
    id: "quiz1-17",
    question: "The theatre company will ___ the play again next month.",
    options: ["A. perform", "B. locate", "C. adapt", "D. review"],
    answer: "A. perform",
  },
  {
    id: "quiz1-18",
    question: "The film was ___ last Friday and quickly became popular.",
    options: ["A. released", "B. performed", "C. located", "D. produced"],
    answer: "A. released",
  },
  {
    id: "quiz1-19",
    question: "The supporting ___ were more interesting than the hero.",
    options: ["A. characters", "B. subtitles", "C. critics", "D. venues"],
    answer: "A. characters",
  },
  {
    id: "quiz1-20",
    question: "The film ___ worked behind the camera to prepare each shot.",
    options: ["A. crew", "B. cast", "C. audience", "D. critic"],
    answer: "A. crew",
  },
];

export const quiz2Questions = [
  {
    id: "quiz2-1",
    question: "The pilot couldn't see the runway, so he had to rely on the ___ to help him land the plane.",
    options: ["A. passengers", "B. routes", "C. terminal", "D. radar"],
    answer: "D. radar",
  },
  {
    id: "quiz2-2",
    question: "They ___ on their one-year-long trip around the world in the winter of 2019.",
    options: ["A. picked up", "B. set off", "C. stopped off", "D. saw off"],
    answer: "B. set off",
  },
  {
    id: "quiz2-3",
    question: "___ who use public transport often arrive at work more relaxed than people who drive.",
    options: ["A. Crews", "B. Journeys", "C. Commuters", "D. Motorists"],
    answer: "C. Commuters",
  },
  {
    id: "quiz2-4",
    question: "I can't ___ the hotel on this map. Can you help me find it?",
    options: ["A. locate", "B. control", "C. touch", "D. take"],
    answer: "A. locate",
  },
  {
    id: "quiz2-5",
    question: "Do you think time travel will be possible in the future? Many scientists believe that we can already travel to other ___!",
    options: ["A. dimensions", "B. courses", "C. runways", "D. routes"],
    answer: "A. dimensions",
  },
  {
    id: "quiz2-6",
    question: "It took more than an hour to board the coach. I had to stand in the ___ for ages!",
    options: ["A. jam", "B. delay", "C. queue", "D. location"],
    answer: "C. queue",
  },
  {
    id: "quiz2-7",
    question: "Our plane had some technical problems, so the pilot had to make an emergency ___.",
    options: ["A. delay", "B. control", "C. runway", "D. landing"],
    answer: "D. landing",
  },
  {
    id: "quiz2-8",
    question: "Good morning. I have to ___ my reservation due to illness. Is it possible to get my deposit back?",
    options: ["A. wait", "B. cancel", "C. book", "D. take"],
    answer: "B. cancel",
  },
  {
    id: "quiz2-9",
    question: "I'm ___ from jetlag after my twelve-hour flight. I think I'll go to bed early.",
    options: ["A. hitting", "B. going", "C. taking", "D. suffering"],
    answer: "D. suffering",
  },
  {
    id: "quiz2-10",
    question: "We ___ sightseeing in Paris. Would you like to see my photos of the Eiffel Tower?",
    options: ["A. went", "B. caught", "C. took", "D. hit"],
    answer: "A. went",
  },
  {
    id: "quiz2-11",
    question: "I don't like places with lots of tourists. I prefer to go off the beaten ___.",
    options: ["A. road", "B. track", "C. route", "D. journey"],
    answer: "B. track",
  },
  {
    id: "quiz2-12",
    question: "There's no need to worry. They'll soon be home safe and ___!",
    options: ["A. wide", "B. sound", "C. around", "D. light"],
    answer: "B. sound",
  },
  {
    id: "quiz2-13",
    question: "Anna can't wait to spend time on the beach. She wants to ___ the sun.",
    options: ["A. light", "B. beat", "C. hit", "D. catch"],
    answer: "D. catch",
  },
  {
    id: "quiz2-14",
    question: "We got up at the crack of ___ to catch the early train. I'm exhausted!",
    options: ["A. day", "B. light", "C. dawn", "D. sun"],
    answer: "C. dawn",
  },
  {
    id: "quiz2-15",
    question: "What time does your flight take ___ tonight? If it's not too late, I can take you to the airport.",
    options: ["A. around", "B. up", "C. off", "D. out"],
    answer: "C. off",
  },
  {
    id: "quiz2-16",
    question: "Is it easy to get ___ Madrid? Is there good public transport or do I need to rent a car?",
    options: ["A. up", "B. out", "C. around", "D. off"],
    answer: "C. around",
  },
  {
    id: "quiz2-17",
    question: "It's 1.00 p.m. We can't check ___ the hotel before 2.00 p.m., so let's go find a place to eat first.",
    options: ["A. in", "B. into", "C. up", "D. inside"],
    answer: "B. into",
  },
  {
    id: "quiz2-18",
    question: "I'm not ___. I like to spend my holiday in the same place every year.",
    options: ["A. anxious", "B. memorable", "C. adventurous", "D. comfortable"],
    answer: "C. adventurous",
  },
  {
    id: "quiz2-19",
    question: "It wasn't a very ___ journey. There wasn't much to do and nothing exciting happened.",
    options: ["A. disastrous", "B. ordinary", "C. harmful", "D. eventful"],
    answer: "D. eventful",
  },
  {
    id: "quiz2-20",
    question: "Today is an important ___ holiday. There are celebrations all over the country.",
    options: ["A. national", "B. package", "C. seasonal", "D. native"],
    answer: "A. national",
  },
  {
    id: "quiz2-21",
    question: "This time last month, we ___ to China! It seems like a long time ago now.",
    options: ["A. used to fly", "B. had been flying", "C. were flying", "D. would fly"],
    answer: "C. were flying",
  },
  {
    id: "quiz2-22",
    question: "___ to your mother about our holiday plans last night?",
    options: ["A. Did you talk", "B. Had you talked", "C. Were you used to talking", "D. Had you been talking"],
    answer: "A. Did you talk",
  },
  {
    id: "quiz2-23",
    question: "When I got home yesterday, it ___ heavily.",
    options: ["A. used to rain", "B. would rain", "C. rained", "D. was raining"],
    answer: "D. was raining",
  },
  {
    id: "quiz2-24",
    question: "By the time we arrived at the station, our train ___, so we had to wait for the next one.",
    options: ["A. had left once", "B. had already left", "C. hadn't left yet", "D. already left"],
    answer: "B. had already left",
  },
  {
    id: "quiz2-25",
    question: "My brother and I ___ fight a lot when we were younger, but now we're close.",
    options: ["A. used", "B. use to", "C. would use", "D. used to"],
    answer: "D. used to",
  },
  {
    id: "quiz2-26",
    question: "Mickey ___ at the company for five years before he finally got a promotion.",
    options: ["A. used to work", "B. have worked", "C. had been working", "D. was working"],
    answer: "C. had been working",
  },
  {
    id: "quiz2-27",
    question: "Before he went to Florida last summer, he ___ the sea!",
    options: ["A. would never see", "B. never used to see", "C. had not been seeing", "D. had never seen"],
    answer: "D. had never seen",
  },
  {
    id: "quiz2-28",
    question: "This was Carol's favourite toy as a child. She ___ play with it for many hours every day.",
    options: ["A. use to", "B. used", "C. would", "D. were"],
    answer: "C. would",
  },
  {
    id: "quiz2-29",
    question: "As soon as the plane landed, I ___ my phone for messages.",
    options: ["A. had checked", "B. had been checking", "C. checked", "D. was checking"],
    answer: "C. checked",
  },
  {
    id: "quiz2-30",
    question: "Laura ___ for more than two hours before Pete finally picked her up from the airport. She was so angry!",
    options: ["A. was waiting", "B. had been waiting", "C. would wait", "D. used to wait"],
    answer: "B. had been waiting",
  },
  {
    id: "quiz2-31",
    question: "Three years ago, we ___ to sell our house and travel around the world.",
    options: ["A. decided", "B. were deciding", "C. have decided", "D. had been deciding"],
    answer: "A. decided",
  },
  {
    id: "quiz2-32",
    question: "Did you ___ go to the theatre often when you lived in London?",
    options: ["A. used", "B. used to", "C. use to", "D. would"],
    answer: "C. use to",
  },
  {
    id: "quiz2-33",
    question: "How long ___ in Madrid before you decided to learn Spanish?",
    options: ["A. would you stay", "B. did you use to stay", "C. were you staying", "D. had you been staying"],
    answer: "D. had you been staying",
  },
  {
    id: "quiz2-34",
    question: "When I called her, she had ___ got home from work.",
    options: ["A. just", "B. since", "C. yet", "D. ever"],
    answer: "A. just",
  },
  {
    id: "quiz2-35",
    question: "Unfortunately, we had already eaten when Keith ___ with a pizza.",
    options: ["A. was arriving", "B. arrived", "C. had arrived", "D. had been arriving"],
    answer: "B. arrived",
  },
  {
    id: "quiz2-36",
    question: "___ I had passed my exams, I applied to three different universities.",
    options: ["A. Before", "B. Already", "C. By the time", "D. Once"],
    answer: "D. Once",
  },
  {
    id: "quiz2-37",
    question: "They met ___ in Peru. They've been friends ever since that trip.",
    options: ["A. as soon as they hiked", "B. once they had hiked", "C. when they had been hiking", "D. while they were hiking"],
    answer: "D. while they were hiking",
  },
  {
    id: "quiz2-38",
    question: "Samantha would ___ to my house every Friday when we were children. We always had so much fun together.",
    options: ["A. come", "B. have been coming", "C. came", "D. coming"],
    answer: "A. come",
  },
  {
    id: "quiz2-39",
    question: "I ___ for my meeting at 11.00 p.m. last night. There was so much to do!",
    options: ["A. was still preparing", "B. still prepared", "C. have been preparing", "D. had always prepared"],
    answer: "A. was still preparing",
  },
  {
    id: "quiz2-40",
    question: "Why was William so tired yesterday morning? ___ all night long?",
    options: ["A. He had travelled", "B. He would travel", "C. Was he travelling", "D. Had he been travelling"],
    answer: "D. Had he been travelling",
  },
];

export const quizQuestions = quiz2Questions;
