import { ImagePlus, LayoutPanelTop, Plus, Trash2, Upload } from "lucide-react";

import { StudioButton, StudioCanvasToolbar, StudioField } from "../../../components/builder-studio/StudioControls.jsx";
import { NativeSingleChoiceHotspotCanvas } from "../../../components/native-single-choice/NativeSingleChoiceHotspotCanvas.jsx";
import { NATIVE_SINGLE_CHOICE_LIMITS } from "../../../data/native-activities/nativeSingleChoice.js";
import { NativeSingleChoiceHotspotBulkImporter } from "./NativeSingleChoiceHotspotBulkImporter.jsx";

const bindingValue = (questionId, optionId) => `${questionId}:${optionId}`;

export function NativeSingleChoiceVisualAuthoring({ presentation, panels, selectedPanel, selectedPanelId, setSelectedPanelId, selectedHotspot, selectedHotspotId, setSelectedHotspotId, questions, zoom, setZoom, uploading, hotspotBinding, setHotspotBinding, mappedBindings, nextHotspotBinding, assetUrlForSlot, enableVisual, disableVisual, importHotspots, addPanel, movePanel, deletePanel, uploadBackground, createHotspot, updateHotspot, updateHotspotArea, updateHotspotGeometry, deleteHotspot, maximumPanels = NATIVE_SINGLE_CHOICE_LIMITS.panels, sharedCanvas = false }) {
  return <section className="native-single-choice-visual-authoring"><header><div><span className="studio-section-icon"><LayoutPanelTop aria-hidden="true" /></span><div><h3>Visual presentation</h3><p>Optional managed backgrounds with option-bound source-pixel hotspots.</p></div></div>{presentation ? <StudioButton variant="danger-ghost" disabled={sharedCanvas} onClick={disableVisual}>Remove visual mode</StudioButton> : <StudioButton variant="primary" onClick={enableVisual}><ImagePlus aria-hidden="true" />Enable visual mode</StudioButton>}</header>
    {presentation ? <><NativeSingleChoiceHotspotBulkImporter hasExistingHotspots={panels.some((panel) => panel.hotspots.length)} onImport={importHotspots} /><div className="studio-visual-workspace"><aside className="studio-navigator"><header><div><LayoutPanelTop aria-hidden="true" /><div><h3>Panels</h3><p>{maximumPanels === 1 ? "One fixed visual panel." : "Visual pages inside part-1."}</p></div></div><span className="studio-count">{panels.length}</span></header><div className="studio-layer-list">{panels.map((panel, index) => <button type="button" key={panel.id} aria-current={panel.id === selectedPanelId ? "true" : undefined} onClick={() => { setSelectedPanelId(panel.id); setSelectedHotspotId(null); }}><span><strong>Panel {index + 1}</strong><small>{panel.backgroundAssetSlot ? `${panel.sourceWidth} × ${panel.sourceHeight}` : "Needs background"}</small></span></button>)}</div>{panels.length < maximumPanels ? <StudioButton onClick={addPanel}><Plus aria-hidden="true" />Add Panel</StudioButton> : null}{selectedPanel && maximumPanels > 1 ? <><StudioButton onClick={() => movePanel(-1)} disabled={panels.indexOf(selectedPanel) === 0}>Move Up</StudioButton><StudioButton onClick={() => movePanel(1)} disabled={panels.indexOf(selectedPanel) === panels.length - 1}>Move Down</StudioButton><StudioButton variant="danger-ghost" onClick={deletePanel}><Trash2 aria-hidden="true" />Delete Panel</StudioButton></> : null}</aside>
      <section className="studio-canvas-column"><StudioCanvasToolbar zoom={zoom} onZoomChange={setZoom} /><div className="studio-canvas-viewport"><div className="studio-artboard-wrap" style={{ width: `${zoom * 100}%` }}>{selectedPanel ? <NativeSingleChoiceHotspotCanvas panel={selectedPanel} assetUrl={assetUrlForSlot(selectedPanel.backgroundAssetSlot)} questions={questions} selectedHotspotId={selectedHotspotId} onSelect={setSelectedHotspotId} onChangeArea={updateHotspotGeometry} onDelete={deleteHotspot} /> : <p>Select a panel.</p>}</div></div></section>
      <aside className="studio-inspector"><header><span className="studio-section-icon"><ImagePlus aria-hidden="true" /></span><div><h3>{selectedHotspot ? "Hotspot properties" : "Panel properties"}</h3><p>{selectedPanel ? `Panel ${panels.indexOf(selectedPanel) + 1}` : "Select a panel."}</p></div></header>{selectedPanel ? <><label className="studio-upload-action"><Upload aria-hidden="true" /><span><strong>{uploading ? "Uploading…" : selectedPanel.backgroundAssetSlot ? "Change background" : "Upload background"}</strong><small>PNG, JPEG or WebP</small></span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading || sharedCanvas} onChange={(event) => { uploadBackground(event.target.files?.[0]); event.target.value = ""; }} /></label><StudioField label="Option to map"><select value={hotspotBinding} onChange={(event) => setHotspotBinding(event.target.value)}><option value="">Next unused option</option>{questions.flatMap((question, questionIndex) => question.options.map((option, optionIndex) => { const value = bindingValue(question.id, option.id); return <option key={value} value={value} disabled={mappedBindings.has(value)}>Question {questionIndex + 1}, option {optionIndex + 1}: {option.text || "Untitled"}</option>; }))}</select></StudioField><StudioButton variant="primary" disabled={!selectedPanel.backgroundAssetSlot || !nextHotspotBinding} reason={!selectedPanel.backgroundAssetSlot ? "Upload a background first" : !nextHotspotBinding ? "Every option already has a hotspot" : ""} onClick={createHotspot}>New hotspot</StudioButton>{selectedHotspot ? <><StudioField label="Hotspot binding"><select value={bindingValue(selectedHotspot.questionId, selectedHotspot.optionId)} onChange={(event) => { const [questionId, optionId] = event.target.value.split(":"); updateHotspot((hotspot) => { hotspot.questionId = questionId; hotspot.optionId = optionId; }); }}>{questions.flatMap((question, questionIndex) => question.options.map((option, optionIndex) => { const value = bindingValue(question.id, option.id); return <option key={value} value={value} disabled={mappedBindings.has(value) && value !== bindingValue(selectedHotspot.questionId, selectedHotspot.optionId)}>Question {questionIndex + 1}, option {optionIndex + 1}: {option.text || "Untitled"}</option>; }))}</select></StudioField><div className="studio-number-grid">{["x", "y", "width", "height"].map((key) => <StudioField key={key} label={key[0].toUpperCase() + key.slice(1)}><input type="number" min={["width", "height"].includes(key) ? 1 : 0} step="1" value={selectedHotspot.area[key]} onChange={(event) => updateHotspotArea(key, event.target.value)} /></StudioField>)}</div><StudioButton variant="danger-ghost" onClick={deleteHotspot}><Trash2 aria-hidden="true" />Delete Hotspot</StudioButton></> : null}</> : <p>Select or add a panel.</p>}</aside></div></> : null}
  </section>;
}
