import { CopyPlus, Trash2 } from "lucide-react";

function id(prefix) { return `${prefix}_${crypto.randomUUID()}`; }
function clamp(value, maximum = 1) { return Math.max(0, Math.min(maximum, Number(value) || 0)); }

export function ImageBackedEditor({ content, assets, onChange }) {
  const fields = content.fields || [];
  const updateField = (fieldId, change) => onChange({ ...content, fields: fields.map((field) => field.id === fieldId ? { ...field, ...change } : field) });
  const move = (field, axis, amount) => { const geometry = { ...field.geometry }; geometry[axis] = clamp(geometry[axis] + amount, 1 - (axis === "x" ? geometry.width : geometry.height)); updateField(field.id, { geometry }); };
  const resize = (field, axis, value) => { const geometry = { ...field.geometry }; geometry[axis] = Math.max(.01, Math.min(Number(value), 1 - (axis === "width" ? geometry.x : geometry.y))); updateField(field.id, { geometry }); };
  const add = () => onChange({ ...content, fields: [...fields, { id: id("field"), kind: "text_input", geometry: { x: .1, y: .1, width: .25, height: .08 }, prompt: "New field" }] });
  return <section className="studio-image-backed-editor"><label>Approved raster background<select value={content.backgroundAssetId || ""} onChange={(event) => onChange({ ...content, backgroundAssetId: event.target.value })}><option value="">Choose background</option>{assets.filter((asset) => asset.mimeType.startsWith("image/")).map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.sourceRelativeIdentity}</option>)}</select></label><button type="button" className="studio-button secondary" onClick={add}><CopyPlus aria-hidden="true" /> Add field</button>
    <div className="studio-image-field-list" aria-label="Accessible image field list">{fields.map((field, index) => <fieldset key={field.id} onKeyDown={(event) => { if (!event.altKey || !["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) return; event.preventDefault(); move(field, ["ArrowLeft", "ArrowRight"].includes(event.key) ? "x" : "y", ["ArrowLeft", "ArrowUp"].includes(event.key) ? -.005 : .005); }}><legend>Field {index + 1}</legend><label>Kind<select value={field.kind} onChange={(event) => updateField(field.id, { kind: event.target.value })}>{["static_label", "single_choice", "text_input", "media_trigger", "linked_text_panel"].map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>Student label or prompt<input value={field.prompt || field.label || field.text || ""} onChange={(event) => updateField(field.id, field.kind === "static_label" ? { label: event.target.value } : field.kind === "linked_text_panel" ? { text: event.target.value } : { prompt: event.target.value })} /></label><div className="studio-geometry-grid">{["x", "y"].map((axis) => <label key={axis}>{axis}<input type="range" min="0" max={1 - (axis === "x" ? field.geometry.width : field.geometry.height)} step="0.005" value={field.geometry[axis]} onChange={(event) => move(field, axis, Number(event.target.value) - field.geometry[axis])} /></label>)}{["width", "height"].map((axis) => <label key={axis}>{axis}<input type="range" min=".01" max="1" step=".005" value={field.geometry[axis]} onChange={(event) => resize(field, axis, event.target.value)} /></label>)}</div><small>Alt + arrow keys nudge the selected field. Coordinates stay normalized.</small><button type="button" className="studio-button danger" onClick={() => onChange({ ...content, fields: fields.filter((item) => item.id !== field.id) })}><Trash2 aria-hidden="true" /> Delete field</button></fieldset>)}</div>
  </section>;
}
