import { ArrowDown, ArrowUp, Copy, Plus, Trash2 } from "lucide-react";

import { ImageBackedEditor } from "./ImageBackedEditor.jsx";

const makeId = (prefix) => `${prefix}_${crypto.randomUUID()}`;
function reorder(items, index, delta) { const next = [...items]; const target = index + delta; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next; }
function Controls({ index, count, onMove, onDuplicate, onRemove }) { return <div className="studio-node-controls"><button type="button" aria-label="Move up" disabled={!index} onClick={() => onMove(-1)}><ArrowUp /></button><button type="button" aria-label="Move down" disabled={index === count - 1} onClick={() => onMove(1)}><ArrowDown /></button><button type="button" aria-label="Duplicate" onClick={onDuplicate}><Copy /></button><button type="button" aria-label="Remove" onClick={onRemove}><Trash2 /></button></div>; }
function QuestionEditor({ content, onChange }) {
  const questions = content.questions || [];
  const setQuestions = (next) => onChange({ ...content, questions: next });
  const update = (id, change) => setQuestions(questions.map((item) => item.id === id ? { ...item, ...change } : item));
  const duplicate = (question) => ({ ...structuredClone(question), id: makeId("question"), options: question.options.map((option) => ({ ...option, id: makeId("option") })) });
  return <div>{questions.map((question, index) => <fieldset key={question.id}><legend>Question {index + 1}</legend><Controls index={index} count={questions.length} onMove={(delta) => setQuestions(reorder(questions, index, delta))} onDuplicate={() => setQuestions([...questions.slice(0, index + 1), duplicate(question), ...questions.slice(index + 1)])} onRemove={() => setQuestions(questions.filter((item) => item.id !== question.id))} /><label>Prompt<textarea value={question.prompt} onChange={(event) => update(question.id, { prompt: event.target.value })} /></label><div className="studio-option-list">{question.options.map((option, optionIndex) => <div key={option.id}><input aria-label={`Option ${optionIndex + 1}`} value={option.text} onChange={(event) => update(question.id, { options: question.options.map((item) => item.id === option.id ? { ...item, text: event.target.value } : item) })} /><Controls index={optionIndex} count={question.options.length} onMove={(delta) => update(question.id, { options: reorder(question.options, optionIndex, delta) })} onDuplicate={() => update(question.id, { options: [...question.options.slice(0, optionIndex + 1), { ...option, id: makeId("option") }, ...question.options.slice(optionIndex + 1)] })} onRemove={() => update(question.id, { options: question.options.filter((item) => item.id !== option.id) })} /></div>)}</div><button type="button" onClick={() => update(question.id, { options: [...question.options, { id: makeId("option"), text: "" }] })}><Plus /> Add option</button></fieldset>)}<button type="button" className="studio-button secondary" onClick={() => setQuestions([...questions, { id: makeId("question"), prompt: "", options: [{ id: makeId("option"), text: "" }, { id: makeId("option"), text: "" }] }])}><Plus /> Add question</button></div>;
}
function TrueFalseEditor({ content, onChange }) { const items = content.statements || []; const set = (next) => onChange({ ...content, statements: next }); return <div>{items.map((item, index) => <fieldset key={item.id}><legend>Statement {index + 1}</legend><Controls index={index} count={items.length} onMove={(delta) => set(reorder(items, index, delta))} onDuplicate={() => set([...items, { ...item, id: makeId("statement") }])} onRemove={() => set(items.filter((entry) => entry.id !== item.id))} /><textarea value={item.prompt} onChange={(event) => set(items.map((entry) => entry.id === item.id ? { ...entry, prompt: event.target.value } : entry))} /></fieldset>)}<button type="button" onClick={() => set([...items, { id: makeId("statement"), prompt: "" }])}><Plus /> Add statement</button></div>; }
function GapEditor({ content, onChange }) { const items = content.items || []; const set = (next) => onChange({ ...content, items: next }); return <div>{items.map((item, index) => <fieldset key={item.id}><legend>Gap {index + 1}</legend><Controls index={index} count={items.length} onMove={(delta) => set(reorder(items, index, delta))} onDuplicate={() => set([...items, { ...structuredClone(item), id: makeId("item"), responseFieldId: makeId("field") }])} onRemove={() => set(items.filter((entry) => entry.id !== item.id))} /><label>Student prompt<textarea value={item.prompt} onChange={(event) => set(items.map((entry) => entry.id === item.id ? { ...entry, prompt: event.target.value } : entry))} /></label></fieldset>)}<button type="button" onClick={() => set([...items, { id: makeId("item"), responseFieldId: makeId("field"), prompt: "", displayGuidance: { case: "", punctuation: "" } }])}><Plus /> Add response field</button></div>; }
function ScrollEditor({ content, assets, onChange }) { const blocks = content.blocks || []; const set = (next) => onChange({ ...content, blocks: next }); return <div>{blocks.map((block, index) => <fieldset key={block.id}><legend>Block {index + 1}</legend><Controls index={index} count={blocks.length} onMove={(delta) => set(reorder(blocks, index, delta))} onDuplicate={() => set([...blocks, { ...block, id: makeId("block") }])} onRemove={() => set(blocks.filter((item) => item.id !== block.id))} /><label>Kind<select value={block.kind} onChange={(event) => set(blocks.map((item) => item.id === block.id ? { id: item.id, kind: event.target.value, ...(event.target.value === "text" ? { text: "" } : { assetId: "", altText: "" }) } : item))}><option value="text">Text</option><option value="image">Image</option></select></label>{block.kind === "text" ? <textarea value={block.text} onChange={(event) => set(blocks.map((item) => item.id === block.id ? { ...item, text: event.target.value } : item))} /> : <><select value={block.assetId} onChange={(event) => set(blocks.map((item) => item.id === block.id ? { ...item, assetId: event.target.value } : item))}>{assets.filter((asset) => asset.mimeType.startsWith("image/")).map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.sourceRelativeIdentity}</option>)}</select><input placeholder="Accessible alt text" value={block.altText} onChange={(event) => set(blocks.map((item) => item.id === block.id ? { ...item, altText: event.target.value } : item))} /></>}</fieldset>)}<button type="button" onClick={() => set([...blocks, { id: makeId("block"), kind: "text", text: "" }])}><Plus /> Add content block</button><label>Optional linked audio<select value={content.linkedAudioAssetId || ""} onChange={(event) => onChange({ ...content, linkedAudioAssetId: event.target.value || undefined })}><option value="">None</option>{assets.filter((asset) => asset.mimeType.startsWith("audio/")).map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.sourceRelativeIdentity}</option>)}</select></label></div>; }

export function ManualActivityContentEditor({ type, content, assets, onChange }) {
  if (type === "multiple_choice") return <QuestionEditor content={content} onChange={onChange} />;
  if (type === "true_false") return <TrueFalseEditor content={content} onChange={onChange} />;
  if (type === "typed_gap_fill") return <GapEditor content={content} onChange={onChange} />;
  if (type === "open_answer") return <><label>Student prompt<textarea value={content.prompt || ""} onChange={(event) => onChange({ ...content, prompt: event.target.value })} /></label><label>Response guidance<input value={content.responseGuidance || ""} onChange={(event) => onChange({ ...content, responseGuidance: event.target.value })} /></label></>;
  if (type === "media_audio" || type === "media_video") return <><label>Approved {type === "media_audio" ? "audio" : "video"} asset<select value={content.assetId || ""} onChange={(event) => onChange({ ...content, assetId: event.target.value })}><option value="">Choose asset</option>{assets.filter((asset) => asset.mimeType.startsWith(type === "media_audio" ? "audio/" : "video/")).map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.sourceRelativeIdentity}</option>)}</select></label><label>Transcript<textarea value={content.transcript || ""} onChange={(event) => onChange({ ...content, transcript: event.target.value })} /></label></>;
  if (type === "scrollable_panel") return <ScrollEditor content={content} assets={assets} onChange={onChange} />;
  return <ImageBackedEditor content={content} assets={assets} onChange={onChange} />;
}
