import { Archive, CheckCircle2, Copy, Eye, Save, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { mutateManualActivity } from "../bookBuilderApi.js";
import { ImageBackedEditor } from "./ImageBackedEditor.jsx";
import { ManualActivityContentEditor } from "./ManualActivityContentEditor.jsx";
import { StudentActivityPreview } from "./StudentActivityPreview.jsx";
import { TeacherSolutionEditor } from "./TeacherSolutionEditor.jsx";

function referencedAssets(activity, assets) { const selected = new Set(); const visit = (value, key = "") => { if (typeof value === "string" && /assetId$/i.test(key) && value) selected.add(value); else if (Array.isArray(value)) value.forEach(visit); else if (value && typeof value === "object") Object.entries(value).forEach(([childKey, child]) => visit(child, childKey)); }; visit(activity.content); return assets.filter((asset) => selected.has(asset.assetId)).map((asset) => ({ assetId: asset.assetId, role: asset.role, mimeType: asset.mimeType, sourceRelativeIdentity: asset.sourceRelativeIdentity, digest: asset.digest, stale: asset.stale })); }

export function ManualActivityEditor({ projectId, initialActivity, expectedRevision, hierarchyOptions, assets, writeEnabled, isNew = false, onCommitted, onClose }) {
  const [draft, setDraft] = useState(() => structuredClone(initialActivity)); const [preview, setPreview] = useState(false); const [dirty, setDirty] = useState(isNew); const [state, setState] = useState({ status: "idle", message: "", validation: null });
  useEffect(() => { const handler = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  const component = hierarchyOptions.find((item) => item.componentKey === draft.hierarchy.componentKey); const group = component?.groups.find((item) => item.unitGroupKey === draft.hierarchy.unitGroupKey);
  const change = (next) => { setDraft(next); setDirty(true); setState({ status: "idle", message: "", validation: null }); };
  const withAssets = useMemo(() => ({ ...draft, assetReferences: referencedAssets(draft, assets) }), [draft, assets]);
  async function validate() { setState({ status: "working", message: "", validation: null }); try { const result = await mutateManualActivity(projectId, "preview", { activity: withAssets }); setState({ status: result.validation.valid ? "success" : "error", message: result.validation.valid ? "Non-writing preview is valid." : "The draft needs attention.", validation: result.validation }); setPreview(true); } catch (error) { setState({ status: "error", message: error.message, validation: null }); } }
  async function commit(operation = isNew ? "create" : "update", activity = withAssets) { setState({ status: "working", message: "", validation: null }); try { const result = await mutateManualActivity(projectId, operation, operation === "create" || operation === "update" ? { activity, expectedRevision, clientMutationId: `mutation_${crypto.randomUUID()}` } : { activityId: draft.activityId, expectedRevision, clientMutationId: `mutation_${crypto.randomUUID()}` }); setDirty(false); setState({ status: "success", message: `${operation} saved as revision ${result.revision}.`, validation: null }); onCommitted(result); } catch (error) { setState({ status: error.code === "project_revision_conflict" ? "conflict" : "error", message: error.message, validation: error.details?.errors ? { errors: error.details.errors } : null }); } }
  const selectComponent = (key) => { const next = hierarchyOptions.find((item) => item.componentKey === key); const first = next?.groups[0]; change({ ...draft, hierarchy: { ...draft.hierarchy, sourceBookRootKey: next.sourceBookRootKey, componentKey: next.componentKey, effectiveComponentRole: next.effectiveComponentRole, unitGroupKey: first?.unitGroupKey || null, unitGroupNumber: first?.unitGroupNumber ?? null } }); };
  const close = () => { if (!dirty || window.confirm("Discard the unsaved manual activity draft?")) onClose(); };
  return <section className="studio-manual-editor" aria-label="Manual activity authoring workspace"><header><div><span className="studio-eyebrow">{isNew ? `New manual draft · ${draft.sourceMode.replaceAll("_", " ")}` : `${draft.sourceMode.replaceAll("_", " ")} · ${draft.status}`}</span><h2>{draft.title || "Untitled manual activity"}</h2><p>{draft.activityId}</p></div><button type="button" className="studio-icon-button" aria-label="Close manual editor" onClick={close}><X /></button></header>
    {!writeEnabled && <div className="studio-content-boundary-banner"><strong>Read-only Student preview</strong><span>No Teacher solution request or mutation controls are rendered.</span></div>}
    {writeEnabled && <div className="studio-manual-editor-grid"><label>Title<input value={draft.title} maxLength="300" onChange={(event) => change({ ...draft, title: event.target.value })} /></label><label>Status<select value={draft.status} onChange={(event) => change({ ...draft, status: event.target.value })}><option value="draft">Draft</option><option value="approved">Approved</option><option value="archived">Archived</option></select></label><label>Component<select value={draft.hierarchy.componentKey} onChange={(event) => selectComponent(event.target.value)}>{hierarchyOptions.map((item) => <option key={item.componentKey} value={item.componentKey}>{item.label}</option>)}</select></label><label>Unit/group<select value={draft.hierarchy.unitGroupKey || ""} onChange={(event) => { const selected = component.groups.find((item) => item.unitGroupKey === event.target.value); change({ ...draft, hierarchy: { ...draft.hierarchy, unitGroupKey: selected.unitGroupKey, unitGroupNumber: selected.unitGroupNumber } }); }}>{component?.groups.map((item) => <option key={item.unitGroupKey} value={item.unitGroupKey}>{item.label}</option>)}</select></label><label className="wide">Student instructions<textarea value={draft.instructions} onChange={(event) => change({ ...draft, instructions: event.target.value })} /></label><label>Viewport<select value={draft.presentation.viewportMode} onChange={(event) => change({ ...draft, presentation: { ...draft.presentation, viewportMode: event.target.value } })}><option value="fit">Fit / no scroll</option><option value="vertical_scroll">Vertical scroll</option><option value="horizontal_scroll">Horizontal scroll</option></select></label><span className="studio-binding-summary">{component?.label} · {group?.label}</span></div>}
    <div className="studio-manual-workspace"><section><h3>Student-visible content</h3>{writeEnabled ? draft.type === "image_backed" ? <ImageBackedEditor content={draft.content} assets={assets} onChange={(content) => change({ ...draft, content })} /> : <ManualActivityContentEditor type={draft.type} content={draft.content} assets={assets} onChange={(content) => change({ ...draft, content })} /> : null}{(!writeEnabled || preview) && <StudentActivityPreview projectId={projectId} activity={withAssets} />}</section>
      {writeEnabled && <aside><h3>Preview &amp; solutions</h3><button type="button" className="studio-button secondary" onClick={validate}><Eye /> Non-writing Student preview</button>{!isNew && <TeacherSolutionEditor projectId={projectId} activity={withAssets} expectedRevision={expectedRevision} onCommitted={onCommitted} />}</aside>}</div>
    {state.status === "conflict" && <div className="studio-decision-alert danger" role="alert"><strong>Revision conflict</strong><p>Your browser draft is preserved. Reload the current project before saving.</p></div>}{state.message && <div className={`studio-decision-alert ${state.status === "success" ? "positive" : state.status === "error" ? "danger" : ""}`} role={state.status === "error" ? "alert" : "status"}><CheckCircle2 /><span>{state.message}</span></div>}{state.validation?.errors?.length > 0 && <ul className="studio-validation-errors">{state.validation.errors.map((error) => <li key={error}>{error}</li>)}</ul>}
    {writeEnabled && <footer className="studio-manual-actions"><button type="button" className="studio-button secondary" onClick={validate}><Eye /> Preview</button><button type="button" className="studio-button primary" disabled={state.status === "working"} onClick={() => commit()}><Save /> {isNew ? "Create draft" : "Save activity"}</button>{!isNew && <><button type="button" className="studio-button secondary" onClick={() => commit("clone")}><Copy /> Clone</button><button type="button" className="studio-button secondary" onClick={() => commit("archive")}><Archive /> Archive</button><button type="button" className="studio-button danger" onClick={() => window.confirm("Permanently remove this manual activity and its Teacher solution from this validation copy?") && commit("remove")}><Trash2 /> Remove</button></>}</footer>}
  </section>;
}
