import { Eye, EyeOff, Save } from "lucide-react";
import { useEffect, useState } from "react";

import { requestManualActivitySolution, updateManualActivitySolution } from "../bookBuilderApi.js";

function emptySolution(activity) {
  const solutions = activity.type === "multiple_choice" ? { questions: [] } : activity.type === "true_false" ? { statements: [] } : ["typed_gap_fill", "image_backed"].includes(activity.type) ? { fields: [] } : activity.type === "open_answer" ? { rubric: null } : {};
  return { schemaVersion: "1.0", activityId: activity.activityId, type: activity.type, solutions, updatedAt: new Date().toISOString() };
}
function solutionEntry(solution, activity, node) {
  if (activity.type === "multiple_choice") return solution.solutions.questions.find((item) => item.questionId === node.id) || { questionId: node.id, correctOptionId: "" };
  if (activity.type === "true_false") return solution.solutions.statements.find((item) => item.statementId === node.id) || { statementId: node.id, correctValue: true };
  if (activity.type === "typed_gap_fill") return solution.solutions.fields.find((item) => item.responseFieldId === node.responseFieldId) || { responseFieldId: node.responseFieldId, acceptedValues: [], normalizationPolicy: "trim_case_insensitive" };
  return solution.solutions.fields.find((item) => item.fieldId === node.id) || (node.kind === "single_choice" ? { fieldId: node.id, correctOptionId: "" } : { fieldId: node.id, acceptedValues: [], normalizationPolicy: "trim_case_insensitive" });
}

export function TeacherSolutionEditor({ projectId, activity, expectedRevision, onCommitted }) {
  const [visible, setVisible] = useState(false); const [solution, setSolution] = useState(null); const [state, setState] = useState({ status: "idle", message: "" });
  useEffect(() => { setVisible(false); setSolution(null); }, [activity.activityId]);
  async function reveal() { setState({ status: "loading", message: "" }); try { setSolution(await requestManualActivitySolution(projectId, activity.activityId)); } catch (error) { if (error.code === "manual_activity_solution_not_found") setSolution(emptySolution(activity)); else { setState({ status: "error", message: error.message }); return; } } setVisible(true); setState({ status: "idle", message: "" }); }
  const nodes = activity.type === "multiple_choice" ? activity.content.questions || [] : activity.type === "true_false" ? activity.content.statements || [] : activity.type === "typed_gap_fill" ? activity.content.items || [] : activity.type === "image_backed" ? (activity.content.fields || []).filter((item) => ["single_choice", "text_input"].includes(item.kind)) : [];
  const update = (node, entry) => { const key = activity.type === "multiple_choice" ? "questions" : activity.type === "true_false" ? "statements" : "fields"; const identity = activity.type === "multiple_choice" ? "questionId" : activity.type === "true_false" ? "statementId" : activity.type === "typed_gap_fill" ? "responseFieldId" : "fieldId"; setSolution((current) => ({ ...current, solutions: { ...current.solutions, [key]: [...(current.solutions[key] || []).filter((item) => item[identity] !== entry[identity]), entry] } })); };
  async function save() { setState({ status: "loading", message: "" }); try { const result = await updateManualActivitySolution(projectId, { activityId: activity.activityId, solution, expectedRevision, clientMutationId: `mutation_${crypto.randomUUID()}` }); setState({ status: "success", message: `Teacher-only solution saved in revision ${result.revision}.` }); onCommitted(result); } catch (error) { setState({ status: "error", message: error.message }); } }
  if (!visible) return <section className="studio-teacher-boundary"><strong>Teacher-only solutions</strong><p>Hidden by default. This narrow request is available only in explicit local edit mode.</p><button type="button" className="studio-button secondary" onClick={reveal}><Eye /> Reveal Teacher editor</button>{state.message && <p role="alert">{state.message}</p>}</section>;
  return <section className="studio-teacher-boundary revealed"><header><strong>Teacher-only · local internal artifact</strong><button type="button" onClick={() => setVisible(false)}><EyeOff /> Hide</button></header>{nodes.map((node) => { const entry = solutionEntry(solution, activity, node); return <label key={node.id}>{node.prompt || node.id}{activity.type === "multiple_choice" || node.kind === "single_choice" ? <select value={entry.correctOptionId} onChange={(event) => update(node, { ...entry, correctOptionId: event.target.value })}><option value="">Choose correct option</option>{node.options.map((option) => <option key={option.id} value={option.id}>{option.text}</option>)}</select> : activity.type === "true_false" ? <select value={String(entry.correctValue)} onChange={(event) => update(node, { ...entry, correctValue: event.target.value === "true" })}><option value="true">True</option><option value="false">False</option></select> : <textarea value={(entry.acceptedValues || []).join("\n")} onChange={(event) => update(node, { ...entry, acceptedValues: event.target.value.split("\n").map((value) => value.trim()).filter(Boolean) })} placeholder="One accepted value per line" />}</label>; })}<button type="button" className="studio-button primary" onClick={save}><Save /> Save Teacher solution</button>{state.message && <p role={state.status === "error" ? "alert" : "status"}>{state.message}</p>}</section>;
}
